sensor:
  - name: ${a_10}
    address: 10
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_11}
    address: 11
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_12}
    address: 12
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_13}
    address: 13
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_14}
    address: 14
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_15}
    address: 15
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_16}
    address: 16
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_100}
    address: 100
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_101}
    address: 101
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_102}
    address: 102
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ${a_103}
    address: 103
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}

number:
  # Changing these will also make you change your yaml files: 
  - name: ${a_0}
    address: 0
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 1
    max_value: 247
    step: 1
  - name: ${a_1}
    address: 1
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 4
    step: 1
  - name: ${a_2}
    address: 2
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 2
    step: 1
