
# RGB LED on GPIO35
light:
  - platform: esp32_rmt_led_strip
    name: "RGB LED"
    id: led
    pin: 35
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812
    restore_mode: ALWAYS_OFF

interval:
  - interval: 5s
    then:
      - lambda: |-
          if (
              id(errorcode_210).state > 0 ||
              id(errorcode_213).state > 0 ||
              id(errorcode_214).state > 0 ||
              id(errorcode_215).state > 0 ||
              id(errorcode_220).state > 0 ||
              id(errorcode_221).state > 0 ||
              id(errorcode_222).state > 0 ||
              id(errorcode_230).state > 0 ||
              id(errorcode_231).state > 0 ||
              id(errorcode_232).state > 0 ||
              id(errorcode_233).state > 0
          ) {
            id(led).turn_on();
            id(led).set_rgb(1.0, 0.0, 0.0);  // Red
          } else if (
              id(errorcode_216).state  > 0 ||
              id(errorcode_217).state  > 0 ||
              id(errorcode_218).state  > 0 ||
              id(errorcode_219).state  > 0 
          ) {
            id(led).turn_on();
            id(led).set_rgb(0.0, 1.0, 0.0);  // Green
          } else if (
              id(errorcode_200).state  > 0 ||
              id(errorcode_201).state  > 0 
          ) {
            id(led).turn_on();
            id(led).set_rgb(0.0, 0.0, 1.0);  // Blue
          } else {
            id(led).turn_off();
          }
