##
# All the fault codes that the unit generates.
# These are writable for reset.
##
sensor:
  - name: ${s_199}
    address: 199
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    entity_category: diagnostic
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    id: errorcode_199
  - name: ${s_200}
    address: 200
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_200
  - name: ${s_201}
    address: 201
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_201
  - name: ${s_202}
    address: 202
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_202
  - name: ${s_203}
    address: 203
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_203
  - name: ${s_210}
    address: 210
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_210
  - name: ${s_211}
    address: 211
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_211
  - name: ${s_212}
    address: 212
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_212
  - name: ${s_213}
    address: 213
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_213
  - name: ${s_214}
    address: 214
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_214
  - name: ${s_215}
    address: 215
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_215
  - name: ${s_216}
    address: 216
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_216
  - name: ${s_217}
    address: 217
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_217
  - name: ${s_218}
    address: 218
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_218
  - name: ${s_219}
    address: 219
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    id: errorcode_219
  - name: ${s_220}
    address: 220
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_220
  - name: ${s_221}
    address: 221
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: ${alert_icon}
    id: errorcode_221
  - name: ${s_222}
    address: 222
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    id: errorcode_222
  - name: ${s_230}
    address: 230
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    id: errorcode_230
  - name: ${s_231}
    address: 231
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    id: errorcode_231
  - name: ${s_232}
    address: 232
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    id: errorcode_232
  - name: ${s_233}
    address: 233
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    id: errorcode_233

number:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    name: "${s_200} - Reset"
    id: HRU_errors1
    address: 200
    value_type: U_WORD
    skip_updates: ${skip_updates.errors}
    use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:air-filter
    min_value: 0
    max_value: ${max.error_number}
    step: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    name: "${s_201} - Reset"
    id: HRU_errors2
    address: 201
    value_type: U_WORD
    use_write_multiple: true
    skip_updates: ${skip_updates.errors}
    entity_category: diagnostic
    icon: mdi:air-filter
    min_value: 0
    max_value: ${max.error_number}
    step: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    name: "${s_202} - Reset"
    id: HRU_errors3_egressFlow
    address: 202
    value_type: U_WORD
    use_write_multiple: true
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    min_value: 0
    max_value: ${max.error_number}
    step: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    name: ${s_203} - Reset
    id: HRU_errors4_ingressFlow
    address: 203
    value_type: U_WORD
    use_write_multiple: true
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    min_value: 0
    max_value: ${max.error_number}
    step: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    name: "${s_222} - Reset"
    address: 222
    value_type: U_WORD
    use_write_multiple: true
    skip_updates: ${skip_updates.errors}
    icon: ${alert_icon}
    entity_category: diagnostic
    min_value: 0
    max_value: ${max.error_number}
    step: 1