sensor:
  # massflow intake
  - name: ${s_2020}
    address: 2020
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  # massflow exhaust
  - name: ${s_2022}
    address: 2022
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  # - name: ${s_3000}
  #   address: 3000
  #   unit_of_measurement: '%'
  #   value_type: U_WORD
  #   register_type: holding
  #   state_class: measurement
  #   platform: modbus_controller
  #   modbus_controller_id: ${modbus_id}
  # - name: ${s_3001}
  #   address: 3001
  #   unit_of_measurement: '%'
  #   value_type: U_WORD
  #   register_type: holding
  #   state_class: measurement
  #   platform: modbus_controller
  #   modbus_controller_id: ${modbus_id}
  - name: ${s_3010}
    address: 3010
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3011}
    address: 3011
    unit_of_measurement: ppm
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:molecule-co2
  - name: ${s_3020}
    address: 3020
    unit_of_measurement: "rpm"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:speedometer
  - name: ${s_3021}
    address: 3021
    unit_of_measurement: "rpm"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:speedometer
  - name: ${s_3022}
    address: 3022
    unit_of_measurement: W
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:lightning-bolt
  - name: ${s_3023}
    address: 3023
    unit_of_measurement: W
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:lightning-bolt
  - name: ${s_3030}
    address: 3030
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3031}
    address: 3031
    unit_of_measurement: kg/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3032}
    address: 3032
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    filters:
      - multiply: 0.1
    icon: mdi:temperature-celsius
    device_class: "temperature"
  - name: ${s_3033}
    address: 3033
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:water-percent
    device_class: "humidity"
  - name: ${s_3040}
    address: 3040
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:valve
  - name: ${s_3050}
    address: 3050
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3051}
    address: 3051
    unit_of_measurement: kg/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3052}
    address: 3052
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    filters:
      - multiply: 0.1
    icon: mdi:temperature-celsius
    device_class: "temperature"
    modbus_controller_id: ${modbus_id}
  - name: ${s_3053}
    address: 3053
    unit_of_measurement: "%"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:water-percent
    device_class: "humidity"
  - name: ${s_3060}
    id: hru_m3h_toevoer_binnen_total
    address: 3060
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    unit_of_measurement: "m3/h"
  - name: ${s_3061}
    address: 3061
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    unit_of_measurement: "kg/h"
  - name: ${s_3062}
    address: 3062
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    filters:
      - multiply: 0.1
    icon: mdi:temperature-celsius
    device_class: "temperature"
  - name: ${s_3063}
    address: 3063
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:water-percent
    device_class: "humidity"
    unit_of_measurement: '%'
  - name: ${s_3070}
    address: 3070
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    unit_of_measurement: "m3/h"
  - name: ${s_3071}
    address: 3071
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    unit_of_measurement: "kg/h"
  - name: ${s_3072}
    address: 3072
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    filters:
      - multiply: 0.1
    icon: mdi:temperature-celsius
    device_class: "temperature"
  - name: ${s_3073}
    address: 3073
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:water-percent
    device_class: "humidity"
    filters:
      - or:
          - delta: 1
          - heartbeat: 60s
      - lambda: |-
          float rand1 = rand() % 1;        
          return x + rand1;
  - name: ${s_3080}
    address: 3080
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3081}
    address: 3081
    unit_of_measurement: "kg/h"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3082}
    address: 3082
    unit_of_measurement: "°C"
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    filters:
      - multiply: 0.1
    icon: mdi:temperature-celsius
    device_class: "temperature"
  - name: ${s_3083}
    address: 3083
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:water-percent
    device_class: "humidity"
    unit_of_measurement: '%'

  - name: ${s_4000}
    address: 4000
    unit_of_measurement: "h"
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.base}
    icon: mdi:clock
    state_class: "total_increasing"
  - name: ${s_4001}
    address: 4001
    unit_of_measurement: "h"
    value_type: U_WORD
    register_type: holding
    state_class: "total_increasing"
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.base}
    icon: mdi:clock
  - name: ${s_4002}
    address: 4002
    unit_of_measurement: "m3"
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.base}
    state_class: "total_increasing"
    icon: mdi:clock
  - name: ${s_4003}
    address: 4003
    unit_of_measurement: "m3"
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.base}
    state_class: "total_increasing"
    icon: mdi:clock

number:
  # BRDG fan:
  - name: ${s_2000}
    address: 2000
    value_type: U_WORD
    min_value: 0
    max_value: 25
    step: 1
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    use_write_multiple: true

switch:
  - name: ${s_2001}
    address: 2001
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    use_write_multiple: true
  - name: ${s_2023}
    address: 2023
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    use_write_multiple: true
  - name: ${s_2021}
    address: 2021
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    use_write_multiple: true

### The connectivity of the zone flaps, does not show up for some reason on my system. YMMV
binary_sensor:
  - name: ${s_3024_z1}
    address: 3024
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3024_z2}
    address: 3024
    bitmask: 1
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3024_z3}
    address: 3024
    bitmask: 2
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${s_3024_z4}
    address: 3024
    bitmask: 3
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
